[colors]
accent = { light = "#AA0032", dark = "#AA0032" }
on-accent = { light = "#ffffff", dark = "#ffffff" }

background = { light = "#ffffff", dark = "#121212" }
on-background =  { light = "#000000", dark = "#ffffff" }

surface = { light = "#efefef", dark = "#181818" }
on-surface = { light = "#000000", dark = "#ffffff" }

destructive = { light = "#C70039 ", dark = "#C70039" }
on-destructive = { light = "#ffffff", dark = "#ffffff" }

[shapes]
border-radius = 8
spacing-factor = 4

[animations]
time = "150ms"

[typography]
line-height-factor = 1.2


[shadows]
