[colors]
primary = "#1d5dea"
on-primary = "#ffffff"
background = "#ffffff"
on-background = "#000000"
surface = "#000000"
destructive = "#EF5A70"

[shapes]
corner-radius = 8
spacing-factor = 4

[animations]
time = "150ms"

[typography]
line-height-factor = 1.2


[shadows]
