mod home;
mod login;
mod table;
mod calendar;
mod menus;
mod searchable_input;
mod signature_field;
mod forms;
mod tabs;
mod dynamic_content;
mod table_of_content;

pub use home::home;
pub use login::login;
pub use table::table;
pub use calendar::calendar;
pub use menus::navigation_and_menus;
pub use searchable_input::searchable_input_page;
pub use signature_field::signature_field;
pub use forms::forms;
pub use tabs::tabs;
pub use dynamic_content::dynamic_content;
pub use table_of_content::table_of_content;
